### ISSUE TITLE
add docker

### ISSUE THREAD

**Issue by butlerx** [redbrick/user-vhost-generator#2]
add a dockerfile and docker-compose

**Comment by zhikiri** [comment]
Hi, @butlerx.
I've just crested PR with docker configuration https://github.com/redbrick/user-vhost-generator/pull/3.

Can you check if it works for you ?

**Comment by Himanshi-Khandelwal** [comment]
@butlerx  I want to work on this issue.

**Comment by Himanshi-Khandelwal** [comment]
@butlerx  can I work on docker-compose file?

**Comment by zhikiri** [comment]
@Himanshi-Khandelwal do we need compose here ? :)

**Comment by butlerx** [comment]
yeah this will be run with a compose file as we use swarm
